my_polls_site/backup/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'my_polls_site.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'polls.views.index', name='index'),
    url(r'^quiz/', 'polls.views.polls', name='polls'),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

my_polls_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

"""
urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', include(admin.site.urls)),
]
"""

# Include namespace in the url's

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^account/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

"""
urlpatterns = [
    url(r'^$', views.index, name='index'),
]
"""


urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/backup/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.answer_text

polls/backup/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def polls(request):
    return render(request, 'polls.html')

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .models import Answer, Question
import random

# Create your views here.

"""

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def polls(request):
    return render(request, 'polls.html')

"""

"""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
        'latest_question_list': latest_question_list,
    })
    return HttpResponse(template.render(context))
"""

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

"""
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)
"""

"""

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_answer = p.answer_set.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        value = 0
        # value = random.randint(1,1000)
        selected_answer.votes = value + 1
        selected_answer.save()
        # Develop An Algorithm to zero out all of the votes
        #votes = 0
        #votes.save()
        #value = 0
        #selected_answer.votes = value
        #selected_answer.save()
        #answers = p.answer_set
        #answers.votes.save()
        #Answer.votes = str[0]
        #Answer.votes.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

"""


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_answer = question.answer_set.get(pk=request.POST['answer'])
    except (KeyError, Answer.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select an answer.",
        })
    else:
        selected_answer.votes += 1
        selected_answer.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))







def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

polls/templates/index.html
<!DOCTYPE html>
<body lang="en">
<head>
<!--<link rel="stylesheet" type="text/css" href="/static/css/my_site_style.css">-->
    <meta charset="UTF-8">
    <title>Django Polls Tutorial</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<style>
a:link {
    color: black;
    background-color: transparent;
    text-decoration: none;
}
a:visited {
    color: blue;
    background-color: transparent;
    text-decoration: none;
}
a:hover {
    color: red;
    background-color: transparent;
    text-decoration: underline;
}
a:active {
    color: purple;
    background-color: transparent;
    text-decoration: underline;
}
</style>

<body>

<!--
<div class="w3-container w3-blue">
{% if request.user.is_authenticated %}
  <h1>Welcome, {% if request.user.first_name %}
      {{ request.user.first.name }}
      {% else %}
      {{ request.user.username }}
      {% endif %}
      To Travel Expense Estimator
  </h1>
{% else %}
{% endif %}
<img src="/static/images/hot_air_balloon.png" style="width:50px;height:50px;">
</div>
-->




<div class="w3-container w3-green">
{% if request.user.is_authenticated %}
  <h1>Welcome {% if request.user.first_name %}
      {{ request.user.first.name }}
      {% else %}
      {{ request.user.username }}
      {% endif %}
      - To Django Polls Tutorial<br>
      <img src="/static/images/polls-icon.png" style="width:50px;height:50px;">
  </h1>
{% else %}
<h1> Welcome To Django Polls Tutorial</h1> <img src="/static/images/polls-icon.png" style="width:50px;height:50px;">
{% endif %}
</div>









<div class="w3-container w3-lime">
<img src="/static/images/django_colored_pattern_background.png" style="width:25" align="right">

<br>
<h3>
<p><a href="http://localhost:8000/" target="_blank">About</a>   <a href="http://localhost:8000/account/register" target="_blank">Register</a>    <a href="http://localhost:8000/account/login/"target="_blank" >Login</a>                                                 </p>
</h3>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p><center>Django Polls Tutorial as found on DjangoProjects.com with some slight enhancements in regards to html5 and css.
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</center>
</p>
</div>











<div class="w3-container w3-green">
  <h5>

  </h5>
  <p><center>Web Design & Application Development By - <a href="http://facebook.com/gil.rael.37/" target="_blank">Gil Rael</a><br>
Software Developed By A Nerd For Nerds</center></p>
</div>
</head>
</body>
</html>

polls/templates/polls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Git Quiz</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<style>
a:link {
    color: black;
    background-color: transparent;
    text-decoration: none;
}
a:visited {
    color: blue;
    background-color: transparent;
    text-decoration: none;
}
a:hover {
    color: red;
    background-color: transparent;
    text-decoration: underline;
}
a:active {
    color: purple;
    background-color: transparent;
    text-decoration: underline;
}
</style>

</head>
<body>

<div class="w3-container w3-blue">
  <h1>Welcome To Travel Expense Estimator</h1><img src="/static/images/hot_air_balloon.png" style="width:50px;height:50px;">
</div>

<!--<img src="/static/python.png" style="width:25">-->

<div class="w3-container w3-yellow">
<img src="/static/images/python_django_gil.png" style="width:25" align="right">

<br>
<h3>
<p><a href="http://localhost:8000/" target="_blank">About</a>   <a href="http://localhost:8000/account/register" target="_blank">Register</a>    <a href="http://localhost:8000/account/login/"target="_blank" >Login</a>     <a href="http://localhost:8000/account/logout/"target="_blank" >Logout</a>                                             </p>
</h3>
<img src="/static/images/sunsetbeach.png" style="width:25" align="left">
<br>
<br>
<br>
<br>
<br>
<!-- May split up text below so that some of the text appears after the submit button-->
<center>Ok let's create a travel expense estimate for your trip.  Please, fill in the blanks below and click submit when your done.<br>
Next check your e-mail at the e-mail address you used to register with at this site.  You should receive a Travel Expense Estimate<br>
in PDF format within a few minutes of clicking the submit button.  The PDF document can be read with the PDF viewer of your choice<br>
Adobe Acrobat Reader is a popular choice and can be obtained here <a href="https://get.adobe.com/reader/" target="_blank">Adobe Acrobat Reader Download</a></center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</center>
<img src="/static/images/travel_banner_one.png" style="width:1260px;height:125px;">
</p>
</div>
<div class="w3-container w3-blue">
  <h5>

  </h5>
  <p><center>Web Design & Application Development By - Gil Rael & Associates LLC<br>
Software Developed By A Nerd For Nerds</center></p>
</div>
</head>
</body>
</html>

polls/templates/polls/detail.html
<!--<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for answer in question.answer_set.all %}
    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
    <label for="answer{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>


{% for answer in question.answer_set.all %}
    {% if answer.votes = value %}
        <h3>You chose {{ answer.answer_text }}</h3>
    {% endif %}
    <li>{{ answer.answer_text }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>